# Generated by Django 2.1.5 on 2019-04-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siadesod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
